products/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

from .views import (
        ProductCreateView,
        ProductDetailView,
        ProductListView,
        ProductUpdateView,
        VendorListView,
    )

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^vendor/$', RedirectView.as_view(pattern_name='products:list'), name='vendor_list'),
    url(r'^vendor/(?P<vendor_name>[\w.@+-]+)/$', VendorListView.as_view(), name='vendor_detail'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailView.as_view(), name='detail_slug'),
]

tags/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import (
		TagDetailView,
		TagListView,
		)

urlpatterns = [
	url(r'^$', TagListView.as_view(), name='list'),
	url(r'^(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name='detail'),
]

products/models.py
from __future__ import unicode_literals
from django.template.defaultfilters import truncatechars
from django.db.models.signals import pre_save, post_save
from django.utils.text import slugify
from django.conf import settings
from django.core.urlresolvers import reverse

from django.db import models

from sellers.models import SellerAccount

from zipcode.models import Zipcode

from category.models import Category

# Create your models here.
class ProductQuerySet(models.query.QuerySet):
	def active(self):
		return self.filter(active=True)


class ProductManager(models.Manager):
	def get_queryset(self):
		return ProductQuerySet(self.model, using=self._db)

	#return all instances in database that are active
	def all(self, *args, **kwargs):
		return self.get_queryset().active()

	def get_related(self, instance):
		products_one = self.get_queryset().filter(categories=instance.categories)
		qs = (products_one).exclude(id=instance.id).distinct()
		return qs

def image_upload_to(instance, filename):
	return "%s/%s" %(instance.slug, filename)

PRODUCT_CONDITION = (
	('new', 'New'),
	('used - like new', 'Used - Like New'),
	('used - very good', 'Used - Very Good'),
	('used - good', 'Used - Good'),
	('used - acceptable', 'Used - Acceptable'),
)

class Product(models.Model):
	seller = models.ForeignKey(SellerAccount)
	title = models.CharField(max_length=120)
	main_img = models.ImageField(null=True, upload_to=image_upload_to)
	slug = models.SlugField(blank=True, unique=True)
	description = models.TextField()
	city = models.CharField(max_length=30, null=True)
	categories = models.ForeignKey(Category, null=True)
	condition = models.CharField(max_length=120, choices=PRODUCT_CONDITION, null=True)
	zipcode = models.ForeignKey(Zipcode)
	price = models.DecimalField(default=9.99, max_digits=100, decimal_places=2, blank=True, null=True)
	active_product = models.BooleanField(default=True)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

	def __unicode__(self):
		return self.title

	def get_absolute_url(self):
		view_name = "products:detail_slug"
		return reverse(view_name, kwargs={"slug": self.slug})

	def get_edit_url(self):
		view_name = "sellers:product_edit"
		return reverse(view_name, kwargs={"slug": self.slug})

	def get_delete_url(self):
		view_name = "sellers:product_delete"
		return reverse(view_name, kwargs={"slug": self.slug})

	@property
	def short_description(self):
		return truncatechars(self.description, 50)

def attachment_upload_to(instance, filename):
	return "%s/%s" %(instance.product, filename)

class Attachment(models.Model):
	product = models.ForeignKey(Product)
	file = models.ImageField(upload_to=attachment_upload_to)


def create_slug(instance, new_slug=None):
	slug = slugify(instance.title)
	if new_slug is not None:
		slug = new_slug
	qs = Product.objects.filter(slug=slug)
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s" %(slug, qs.first().id)
		return create_slug(instance, new_slug=new_slug)
	return slug


def product_pre_save_reciever(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = create_slug(instance)

pre_save.connect(product_pre_save_reciever, sender=Product)



class CuratedProducts(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	section_name = models.CharField(max_length=120)
	products = models.ManyToManyField(Product, blank=True)
	active = models.BooleanField(default=True)

	def __unicode__(self):
		return self.section_name

products/forms.py
from django import forms

from .models import Product, Attachment
# from category.models import Category

from multiupload.fields import MultiFileField


class ProductFilterForm(forms.Form):
	q = forms.CharField(label='Search', required=False)
	location = forms.CharField(label='Location (City & State or Zipcode)', required=False)
	distance_from = forms.CharField(label='Distance From Location (Miles)', widget=forms.TextInput(attrs={'type':'number'}), required=False)
	max_price = forms.DecimalField(decimal_places=2, max_digits=12, required=False)
	min_price = forms.DecimalField(decimal_places=2, max_digits=12, required=False)


class ProductModelForm(forms.ModelForm):
	zip_code_data = forms.CharField(label="Zip Code", required=True, max_length=5)

	#handle the multiple images
	files = MultiFileField(label="Images (Up to 30)", min_num=0, max_num=30, max_file_size=1024*1024*5)
	def save(self, commit=True):
		instance = super(ProductModelForm, self).save(commit)
		for each in self.cleaned_data['files']:
			Attachment.objects.create(file=each, product=instance)
		return instance

	class Meta:
		model = Product
		fields = [
			"title",
			"city",
			"description",
			"categories",
			"condition",
			# "media",
			"main_img",
			"files",
			"price",
			# "tags",
		]
		widgets = {
			"description": forms.Textarea(
					attrs={
						"placeholder": "Description"
					}
				),
			"title": forms.TextInput(
					attrs={
						"placeholder": "Title"
					}
				),
			"city": forms.TextInput(
					attrs={
						"placeholder": "City/Town"
					}
				)
		}

	def clean(self, *args, **kwargs):
		cleaned_data = super(ProductModelForm, self).clean(*args, **kwargs)
		return cleaned_data

	def clean_price(self):
		price = self.cleaned_data.get("price")
		if price < 0:
			raise forms.ValidationError("Price must be >= to $0.00")
		else:
			return price

	def clean_title(self):
		title = self.cleaned_data.get("title")
		if len(title) > 3:
			return title
		else:
			raise forms.ValidationError("Title must be greater than 3 characters long.")

class ProductModelUpdateForm(forms.ModelForm):
	zip_code_data = forms.CharField(label="Zip Code", required=True, max_length=5)

	class Meta:
		model = Product
		fields = [
			"title",
			"city",
			"description",
			"categories",
			"condition",
			"price",
		]
		widgets = {
			"description": forms.Textarea(
					attrs={
						"placeholder": "Description"
					}
				),
			"title": forms.TextInput(
					attrs={
						"placeholder": "Title"
					}
				),
			"city": forms.TextInput(
				attrs={
					"placeholder": "City/Town"
				}
			)
		}

	def clean(self, *args, **kwargs):
		cleaned_data = super(ProductModelUpdateForm, self).clean(*args, **kwargs)
		return cleaned_data

	def clean_price(self):
		price = self.cleaned_data.get("price")
		if price < 0:
			raise forms.ValidationError("Price must be >= to $0.00")
		else:
			return price

	def clean_title(self):
		title = self.cleaned_data.get("title")
		if len(title) > 3:
			return title
		else:
			raise forms.ValidationError("Title must be greater than 3 characters long.")

products/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, JsonResponse
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import View
from django.core.urlresolvers import reverse
from django.core.exceptions import ImproperlyConfigured

#for django_filters
from django_filters import FilterSet, CharFilter, NumberFilter

#local imports
from .models import Product, Attachment
from .forms import ProductModelForm, ProductFilterForm, ProductModelUpdateForm
from .mixins import ProductManagerMixin
# from tags.models import Tag
# from analytics.models import TagView
from sellers.models import SellerAccount

#external imports
from listlist.mixins import (
		MultiSlugMixin,
		SubmitBtnMixin,
		LoginRequiredMixin,
		HeaderFormMixin,
	)

from zipcode.models import Zipcode
from zipcode.math_to_degrees import change_in_latitude, change_in_longitude

from sellers.mixins import SellerAccountMixin

# Create your views here.

class ProductCreateView(HeaderFormMixin, SellerAccountMixin, SubmitBtnMixin, CreateView):
	model = Product
	template_name = "form.html"
	form_class = ProductModelForm
	# success_url = "/products/add/"
	submit_btn = "Add Product"
	form_title = "Add Product"

	#when product is created attach user to product
	def form_valid(self, form):
		seller = self.get_account()
		form.instance.seller = seller
		zip_code_data = form.cleaned_data.get("zip_code_data")
		if zip_code_data:
			zipcode_obj, created = Zipcode.objects.get_or_create(zipcode=zip_code_data)
			form.instance.zipcode = zipcode_obj

		return super(ProductCreateView, self).form_valid(form)


class ProductUpdateView(HeaderFormMixin, ProductManagerMixin, SubmitBtnMixin, MultiSlugMixin, UpdateView):
	model = Product
	template_name = "form.html"
	form_class = ProductModelUpdateForm
	# success_url = "/products/"
	submit_btn = "Update Product"
	form_title = "Update Product"

	def get_initial(self):
		initial = super(ProductUpdateView,self).get_initial()

		#generate zipcode data
		zipcode = self.get_object().zipcode
		initial["zip_code_data"] = zipcode
		return initial

	def form_valid(self, form):
		obj = self.get_object()
		obj.tag_set.clear()

		# product = Product.objects.get(id=product_id)
		zip_code_data = form.cleaned_data.get("zip_code_data")
		if zip_code_data:
			zipcode_obj, created = Zipcode.objects.get_or_create(zipcode=zip_code_data)
			form.instance.zipcode = zipcode_obj

		return super(ProductUpdateView, self).form_valid(form)

class ProductDeleteView(ProductManagerMixin, DeleteView):
	model = Product

	def get_success_url(self):
		return reverse("sellers:product_list")

class ProductDetailView(MultiSlugMixin, DetailView):
	model = Product

	def get_context_data(self, *args, **kwargs):
		context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
		obj = self.get_object()

		return context


class SellerProductListView(SellerAccountMixin, ListView):
	model = Product
	template_name = "sellers/product_list_view.html"
	#paginate the seller list edit view
	paginate_by = 10

	def get_queryset(self, *args, **kwargs):
		qs = super(SellerProductListView, self).get_queryset(**kwargs)
		qs = qs.filter(seller=self.get_account()).order_by("-timestamp")
		query = self.request.GET.get("q")
		if query:
			qs = qs.filter(
					Q(title__icontains=query)|
					Q(description__icontains=query)
				).order_by("-timestamp")
		return qs


class VendorListView(ListView):
	model = Product
	template_name = "products/product_list.html"
	paginate_by = 12

	def get_object(self):
		username= self.kwargs.get("vendor_name")
		seller = get_object_or_404(SellerAccount, user__username=username)
		return seller

	def get_context_data(self, *args, **kwargs):
		context = super(VendorListView, self).get_context_data(*args, **kwargs)
		context["vendor_name"] = str(self.get_object().user.username)
		context["filter_form"] = ProductFilterForm(data=self.request.GET or None)
		return context

	def get_queryset(self, *args, **kwargs):
		seller = self.get_object()
		qs = super(VendorListView, self).get_queryset(**kwargs).filter(seller=seller).order_by("-timestamp")
		query = self.request.GET.get("q")
		if query:
			qs = qs.filter(
					Q(title__icontains=query)|
					Q(description__icontains=query)
				).order_by("-timestamp")
		return qs


class ProductFilter(FilterSet):
	title = CharFilter(name='title', lookup_type='icontains', distinct=True)
	min_price = NumberFilter(name='price', lookup_type='gte', distinct=True) # (some_price__gte=somequery)
	max_price = NumberFilter(name='price', lookup_type='lte', distinct=True)
	class Meta:
		model = Product
		fields = [
			'min_price',
			'max_price',
			'title',
			'description',
		]

class FilterMixin(object):
	filter_class = None
	search_ordering_param = "ordering"

	def get_queryset(self, *args, **kwargs):
		try:
			qs = super(FilterMixin, self).get_queryset(*args, **kwargs)
			return qs
		except:
			raise ImproperlyConfigured("You must have a queryset in order to use the FilterMixin")

	def get_context_data(self, *args, **kwargs):
		context = super(FilterMixin, self).get_context_data(*args, **kwargs)
		qs = self.get_queryset()
		ordering = self.request.GET.get(self.search_ordering_param)
		if ordering:
			qs = qs.order_by(ordering)
		filter_class = self.filter_class
		if filter_class:
			f = filter_class(self.request.GET, queryset=qs)
			context["object_list"] = f
		return context

from django.contrib.gis.geos import Point
from django.contrib.gis.measure import D
from geopy.geocoders import Nominatim
geolocator = Nominatim()


class ProductListView(FilterMixin, ListView):
	model = Product
	paginate_by = 12
	filter_class = ProductFilter

	def get_context_data(self, *args, **kwargs):
		context = super(ProductListView, self).get_context_data(*args, **kwargs)
		context["filter_form"] = ProductFilterForm(data=self.request.GET or None)
		return context

	def get_queryset(self, *args, **kwargs):
		qs = super(ProductListView, self).get_queryset(**kwargs).order_by("-timestamp")
		query = self.request.GET.get("q")

		#location for distance
		user_location = self.request.GET.get("location")
		distance = self.request.GET.get('distance_from')

		if user_location and distance:
			#get distance in miles and turn into degrees
			user_distance = change_in_longitude(change_in_latitude(int(distance)), int(distance))
			#turn user location into geopy Code
			location = geolocator.geocode("%s" %(user_location))
			user_lat_lon = Point(location.longitude, location.latitude)
			#run query
			zipcodes = Zipcode.objects.filter(geom__dwithin=(user_lat_lon, user_distance))
			raw_zipcode_list = [x.zipcode for x in zipcodes]
			products = qs.filter(
				Q(zipcode__zipcode__in=raw_zipcode_list)
			).order_by("-timestamp")
			return products

		if query:
			qs = qs.filter(
					Q(title__icontains=query)|
					Q(description__icontains=query)|
					Q(seller__user__username__icontains=query)|
					Q(city__icontains=query)
				).order_by("-timestamp")

		return qs

templates/products/product_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Product</h1>
  <form class="" action="" method="POST">
    {% csrf_token %}
    <p class="lead">Are you sure you want to delete "{{ object }}"</p>
    <button class="btn btn-danger" type="submit" name="button">Confirm Delete <i class="fa fa-trash"></i></button>
    <a class="btn btn-default" href="{% url 'sellers:product_list' %}">Cancel <i class="fa fa-undo"></i></a>
  </form>

{% endblock content %}

templates/products/product_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
  {{ object.title|title }} | {{ block.super }}
{% endblock head_title %}

{% block content %}
<style media="screen">
  /* .modal-fullscreen */
  .modal-fullscreen .modal-content {
    background: #ffffff;
    border: 0;
    -webkit-box-shadow: none;
    box-shadow: none;
  }

  /* .modal-fullscreen size: we use Bootstrap media query breakpoints */

  .modal-fullscreen .modal-dialog {
    margin: 0;
    margin-right: auto;
    margin-left: auto;
    width: 100%;
  }
  @media (min-width: 768px) {
    .modal-fullscreen .modal-dialog {
      width: 750px;
    }
  }
  @media (min-width: 992px) {
    .modal-fullscreen .modal-dialog {
      width: 970px;
    }
  }
  @media (min-width: 1200px) {
    .modal-fullscreen .modal-dialog {
      width: 1170px;
    }
  }
</style>


<div class="row">
  <div class="col-sm-12">
    <h1>{{ object.title|title }} <small>posted by: <a href='{{ object.seller.get_absolute_url }}'>{{ object.seller.user.username|capfirst }}</a> </small></h1>
    <hr>
  </div>
  <div class="col-sm-8">
    <img class="img-responsive" src="{{ object.main_img.url }}" />
    <br>
    <a href="" data-toggle="modal" data-target="#modal-fullscreen" class="btn btn-primary">View All Images <i class="fa fa-picture-o"></i></a>
    <hr>
    <div class="modal modal-fullscreen fade" id="modal-fullscreen" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h3 class="modal-title" id="myModalLabel">{{ object.title|title }} - <small>{{ object.seller.user.username|capfirst }}</small></h3>
          </div>
          <div class="modal-body">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
              <!-- Indicators -->
              <ol class="carousel-indicators">
                {% for image in object.attachment_set.all %}
                  <li data-target="#myCarousel" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %} active{% endif %}"></li>
                {% endfor %}
              </ol>

              <!-- Wrapper for slides -->
              <div class="carousel-inner" role="listbox">
                {% for image in object.attachment_set.all %}
                  <div class="item{% if forloop.first %} active{% endif %}">
                    <img style="margin-left:auto; margin-right:auto;" class="img-responsive" src="{{ image.file.url }}" />
                  </div>
                {% endfor %}
              </div>

              <!-- Left and right controls -->
              <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span style="top:50%; position:absolute;" aria-hidden="true"><i class="fa fa-chevron-circle-left"></i></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span style="top:50%; position:absolute;" aria-hidden="true"><i style="margin-left: -25px;" class="fa fa-chevron-circle-right"></i></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-sm-4">
    <a class="btn btn-success btn-block" href="mailto:{{ object.seller.user.email }}">Email: {{ object.seller.user|capfirst }} <i class="fa fa-envelope"></i></a>
    <!-- <br>
    <a href="" data-clipboard-text="{{ object.seller.user.email }}" class="btn btn-info btn-block">Copy Email to Clipboard <i class="fa fa-clipboard"></i></a> -->
    <hr>
    <p class="lead">{{ object.description|linebreaks }}</p>
    <p class="lead text-success">${{ object.price }}</p>
  </div>
  <div class="col-sm-12">
    <h3>Comments/Questions</h3>
    <hr>
    <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div>
  </div>
</div>

{% endblock content %}

templates/products/product_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row">
  <div class="col-sm-12">
    <h1>{% if vendor_name %}{{ vendor_name|capfirst }} {% endif %}Products</h1>
  </div>
</div>

<hr>

<div class="row">
  <div class="col-sm-2">
    <form method="GET" action="{% url 'products:list' %}">
      {{ filter_form|crispy }}
      <button type='submit' class='btn btn-success'>Apply Filters <i class="fa fa-plus"></i></button>
    </form>
    <br>
    <a class="btn btn-warning" href="{% url 'products:list' %}">Clear Filters <i class="fa fa-refresh"></i></a>
  </div>
  <div class="col-sm-10">
    {% include "products/product_list_snippet.html" with product_list=object_list %}
  </div>
</div>



{% if is_paginated %}
<ul class="pagination nav navbar-nav">
  {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><i class="fa fa-arrow-left"></i></a></li>
  {% endif %}
  {% if page_obj.paginator.num_pages > 1 %}
    {% for page in page_obj.paginator.page_range %}
      <li class="{% if page_obj.number == page  %}active{% endif %}"><a href="?page={{ page }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ page }}</a></li>
    {% endfor %}
  {% endif %}
  {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><i class="fa fa-arrow-right"></i></a></li>
  {% endif %}
</ul>
{% endif %}

{% endblock content %}

templates/products/product_list_snippet.html
<div class="row">
{% for instance in product_list %}
<div class="col-sm-3">
  <div class="thumbnail">
    <a href="{{ instance.get_absolute_url }}"><img class="img-responsive" src="{{ instance.main_img.url }}" /></a>
    <div class="caption">
      <h3 style="margin-bottom:0;">{{ instance.title|title }} <small>{{ instance.condition|title }}</small></h3>
      <p style="margin-bottom:0;" class="lead text-success"><i class="fa fa-usd"></i>{{ instance.price }}</p>
      <p style="margin-bottom:0;"><i class="fa fa-bars"></i> {{ instance.categories }}</p>
      <p style="margin-bottom:0;"><i class="fa fa-user"></i> {{ instance.seller|capfirst }}</p>
      <p style="margin-bottom:0;"><i class="fa fa-map-marker"></i> {{ instance.city|title }}</p>
      <p style="margin-bottom:0;"><i class="fa fa-calendar"></i> {{ instance.timestamp|timesince }} ago</p>
      <p>{{ instance.description|truncatechars:25 }}</p>
      <p><a href="{{ instance.get_absolute_url }}" class="btn btn-primary" role="button">View More</a></p>
    </div>
  </div>
</div>
{% cycle '' '' '' '</div><div class="row">' %}
{% empty %}
  <div class="col-md-12">
    <p class="lead">No Products found.</p>
  </div>
{% endfor %}
</div>