category/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', views.CategoryListView.as_view(), name='category_home'),
    url(r'^(?P<slug>[\w-]+)/$', views.CategoryDetailView.as_view(), name='category_detail'),
]

listlist/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.gis import admin
from django.conf import settings

#import my app views
from products import urls as products_urls
from category import urls as urls_categories
# from tags import urls as tags_urls
from dashboard.views import DashboardView, LegalView
from sellers import urls as sellers_urls
from contact.views import ContactCreateView

from posts import urls as post_urls


urlpatterns = [
    #handle dashboard views
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    #handle django registration redux
    url(r'^accounts/', include('registration.backends.default.urls')),
    #handle admin sites
    url(r'^admin/', include(admin.site.urls)),
    #handle products app
    url(r'^classifieds/', include(products_urls, namespace='products')),
    #handle sellers app
    url(r'^seller/', include(sellers_urls, namespace='sellers')),
    #handle categories
    url(r'^categories/', include(urls_categories, namespace='categories')),
    #blog app
    url(r'^posts/', include(post_urls, namespace="posts")),
    #contact app
    url(r'^contact/$', ContactCreateView.as_view(), name="contact"),
    #dashboard legal view
    url(r'^legal/$', LegalView.as_view(), name='legal'),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tags/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import (
		TagDetailView,
		TagListView,
		)

urlpatterns = [
	url(r'^$', TagListView.as_view(), name='list'),
	url(r'^(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name='detail'),
]

category/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.text import slugify
from django.core.urlresolvers import reverse

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=120, unique=True)
    slug = models.SlugField(unique=True)
    description = models.TextField(null=True, blank=True)
    active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    class Meta:
        ordering = ["title"]

    def __unicode__(self):
        return self.title


    def get_absolute_url(self):
        return reverse("categories:category_detail", kwargs={"slug": self.slug})

    def get_category_image_url(self):
        img = self.categoryimage_set.first()
        if img:
            return img.image.url
        return img


def image_upload_to_category(instance, filename):
    title = instance.category.title
    slug = slugify(title)
    basename, file_extension = filename.split(".")
    new_filename = "%s-%s.%s" % (basename, instance.id, file_extension)
    return "categories/%s/%s" % (slug, new_filename)

class CategoryImage(models.Model):
    category = models.ForeignKey(Category)
    image = models.ImageField(upload_to=image_upload_to_category)

    def __unicode__(self):
        return self.category.title

category/views.py
from django.shortcuts import render

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .models import Category

# Create your views here.
class CategoryListView(ListView):
	model = Category
	queryset = Category.objects.all()
	# template_name = "products/product_list.html"


class CategoryDetailView(DetailView):
	model = Category

	def get_context_data(self, *args, **kwargs):
		context = super(CategoryDetailView, self).get_context_data(*args, **kwargs)
		obj = self.get_object()
		#order products in category page by date posted
		product_set = obj.product_set.all().order_by("-timestamp")
		products = product_set.distinct()
		context["products"] = products
		return context

templates/category/category_detail.html
{% extends 'base.html' %}

{% block head_title %}
  {{ object }} | {{ block.super }}
{% endblock head_title %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      <h2>{{ object }} <small><a href="{% url 'categories:category_home' %}">- Back To Categories</a></small></h2>
      <hr/>
    </div>
    <div class="col-md-12">
      {% include "products/product_list_snippet.html" with product_list=products %}
    </div>
  </div>
{% endblock content %}

templates/category/category_list.html
{% extends 'base.html' %}

{% block head_title %}
  Categories | {{ block.super }}
{% endblock head_title %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h2>Categories</h2>
    <hr/>
  </div>
  <div class="col-md-offset-3 col-md-6">
    <table class="table">
      <thead>
        <tr>
          <th>Category</th>
        </tr>
      </thead>
      <tbody>
        {% for obj in object_list %}
          <tr>
            <!-- <img src="{{ obj.get_category_image_url }}" /> -->
            <td><a href="{{ obj.get_absolute_url }}">{{ obj }}</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}