listlist/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.gis import admin
from django.conf import settings

#import my app views
from products import urls as products_urls
from category import urls as urls_categories
# from tags import urls as tags_urls
from dashboard.views import DashboardView, LegalView
from sellers import urls as sellers_urls
from contact.views import ContactCreateView

from posts import urls as post_urls


urlpatterns = [
    #handle dashboard views
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    #handle django registration redux
    url(r'^accounts/', include('registration.backends.default.urls')),
    #handle admin sites
    url(r'^admin/', include(admin.site.urls)),
    #handle products app
    url(r'^classifieds/', include(products_urls, namespace='products')),
    #handle sellers app
    url(r'^seller/', include(sellers_urls, namespace='sellers')),
    #handle categories
    url(r'^categories/', include(urls_categories, namespace='categories')),
    #blog app
    url(r'^posts/', include(post_urls, namespace="posts")),
    #contact app
    url(r'^contact/$', ContactCreateView.as_view(), name="contact"),
    #dashboard legal view
    url(r'^legal/$', LegalView.as_view(), name='legal'),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tags/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import (
		TagDetailView,
		TagListView,
		)

urlpatterns = [
	url(r'^$', TagListView.as_view(), name='list'),
	url(r'^(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name='detail'),
]

analytics/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.db import models

# Create your models here.

from tags.models import Tag


# this class and function makes it so that you can add a counter to the tags viewed easier
class TagViewManager(models.Manager):
	def add_count(self, user, tag):
		obj, created = self.model.objects.get_or_create(user=user,
			tag=tag)
		obj.count += 1
		obj.save()
		return obj


class TagView(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
	tag = models.ForeignKey(Tag)
	count = models.IntegerField(default=0)

	objects = TagViewManager()

	def __unicode__(self):
		return str(self.tag.title)

analytics/views.py
from django.shortcuts import render

# Create your views here.

templates/analytics.html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-73152345-1', 'auto');
  ga('send', 'pageview');

</script>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="{% block meta-description %} {% endblock meta-description %}">
    <meta name="author" content="Josh Higgins">
    <meta property="fb:admins" content="1230468748"/>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <title>{% block head_title %}ListList - The Classified Advertisment Website. Gun Listings Welcome!{% endblock head_title %}</title>
    <style>
      {% block css %}
      {% endblock css %}
    </style>
    {% include 'analytics.html' %}

    {% include 'head_css.html' %}
  </head>
  <body>
    {% include 'facebook.html' %}

    {% include 'navbar.html' %}

    {% if messages %}
      <div class="container">
        <div class="col-md-6 col-md-offset-3">
          {% for message in messages %}
            <div style="margin-top:15px; text-align:center;" class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              {{ message }}
            </div>
          {% endfor %}
        </div>
      </div>
    {% endif %}

    {% block jumbotron %}
    {% endblock jumbotron %}

    <div class="container">
      {% block content %}
      {% endblock content %}

      {% block bottom_content %}
      {% endblock bottom_content %}

      {% include 'footer.html' %}
    </div> <!-- /container -->

    {% include 'javascript.html' %}
    <script>
      $(document).ready(function(){
        {% block jquery %}
        {% endblock jquery %}
      });
    </script>
  </body>
</html>

templates/facebook.html
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

templates/footer.html
<footer id="give-me-room">
  <hr>
  <div class="row">
    <div class="col-sm-3">
      <p class="lead footer_border">Social Media</p>
      <a target="_blank" href="https://www.facebook.com/listlistsale/"><p><i class="fa fa-facebook-official"></i> Facebook</p></a>
      <a target="_blank" href="https://www.instagram.com/listlist.sale/"><p><i class="fa fa-instagram"></i> Instagram</p></a>
      <a target="_blank" href="https://www.pinterest.com/listlistsale/"><p><i class="fa fa-pinterest"></i> Pinterest</p></a>
      <a target="_blank" href="https://twitter.com/ListListSale"><p class="last"><i class="fa fa-twitter"></i> Twitter</p></a>
    </div>
    <div class="col-sm-3">
      <p class="lead footer_border">News</p>
      <a href="{% url 'posts:list' %}"><p><i class="fa fa-rss"></i> Blog</p></a>
      <a href="/posts/about-us/"><p><i class="fa fa-users"></i> About Us</p></a>
      <a href="{% url 'contact' %}"><p class="last"><i class="fa fa-comment"></i> Contact</p></a>
    </div>
    <div class="col-sm-3">
      <p class="lead footer_border">More</p>
      <a href="{% url 'posts:list' %}?q=update"><p><i class="fa fa-code"></i> Recent Updates</p></a>
      <!-- <a href="#"><p><i class="fa fa-credit-card-alt"></i> Donate</p></a> -->
      <a href="{% url 'legal' %}"><p class="last"><i class="fa fa-gavel"></i> Terms and Conditions</p></a>
    </div>
    <div class="col-sm-3">
      <p class="lead footer_border">Help</p>
      <a href="/posts/creating-account/"><p><i class="fa fa-user-plus"></i> Creating Account</p></a>
      <a href="/posts/creating-ad/"><p class="last"><i class="fa fa-clipboard"></i> Creating Ad</p></a>
    </div>
  </div>
  <hr/>
  <div class="row">
    <div class="col-md-12">
      <p>&copy; 2016 ListList, LLC.</p>
    </div>
  </div>
</footer>

templates/form.html
{% extends 'base.html' %}

{% block content %}
  {% include 'form_include.html' with form=form submit_btn=submit_btn %}
{% endblock content %}

templates/form_include.html
{% load crispy_forms_tags %}
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    {% if form_title %}
    <h1>{{ form_title }}</h1>
    <hr>
    {% endif %}
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-default btn-block">{% if submit_btn %}{{ submit_btn }}{% else %}Submit{% endif %}</button>
    </form>
  </div>
</div>

templates/head_css.html
{% load staticfiles %}

<!-- Font Awesome -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

<!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">

<!-- My custom styles for ListList -->
<link href="{% static 'css/custom.css' %}" rel="stylesheet">

<!-- Custom styles for navbar -->
<link href="{% static 'css/navbar-top.css' %}" rel="stylesheet">

<!-- For column all -->
<link href="{% static 'css/col-all.css' %}" rel="stylesheet">

<!-- Google Fonts -->
<link href='https://fonts.googleapis.com/css?family=Open+Sans|Ubuntu' rel='stylesheet' type='text/css'>

templates/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}


{% block head_title %}
  Home | {{ block.super }}
{% endblock head_title %}


{% block jumbotron %}
  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1 style="margin-top:0;">Hello, world!</h1>
          <p>This website is currently in production. If you have stumbled here by accident please check back with us later. The site is scheduled to be complete by the end of February; we hope to see you then!</p>
          <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn More &raquo;</a></p>
        </div>
        <div class="col-md-6">
          <video width="100%" controls>
            <source src="#" type="video/mp4">
            <source src="#" type="video/ogg">
            Your browser does not support HTML5 video.
          </video>
        </div>
      </div>
    </div>
  </div>
{% endblock jumbotron %}

{% block content %}
{% endblock content %}

templates/javascript.html
{% load staticfiles %}
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://js.braintreegateway.com/v2/braintree.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
<!-- Jquery -->
<script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script src="{% static 'js/custom.js' %}"></script>
<!--Copy to clipboard-->
<script src="https://cdn.jsdelivr.net/clipboard.js/1.5.8/clipboard.min.js"></script>

templates/legal.html
<ol>
  <li>
    I am 18 years of age or older.
  </li>
  <li>
    I understand that ListList DOES NOT become involved in transactions between parties and does not certify, investigate, or in any way guarantee the legal capacity of any party to transact.
  </li>
  <li>
    I am responsible for obeying all applicable enforcement mechanisms, including, but not limited to federal, state, municipal, and tribal statutes, rules, regulations, ordinances, and judicial decisions, any applicable Presidential Executive Orders, including compliance with all applicable licensing requirements.
  </li>
  <li>
    I will not use ListList.com for any illegal purpose.
  </li>
  <li>
    If I am at all unsure about firearm sales or transfers, I will contact the Bureau of Alcohol, Tobacco, Firearms, and Explosive at 1-800-ATF-GUNS and visit the ATF website at http://www.atf.gov.
  </li>
  <li>
    I will help to ensure the overall openness and accessibility of the site to all users through a peer-review process. I understand that failure to adhere to proper internet protocol and etiquette may result in removal of my listings or more severe corrective action.
  </li>
  <li>
    ListList may edit or remove information, including my listings, from the site without notice.
  </li>
  <li>
    If I violate these terms, ListList may permanently remove me from the site or, depending on the nature and severity of the violation, avail itself of such remedies as are prescribed by law. Whilst ListList ABSOLUTELY BELIEVES AND CHAMPIONS "the right of the people to keep and bear Arms," ListList will comply with federal, state, municipal, and tribal law enforcement entities pursuant to the Constitution of the United States and Due Process of Law.
  </li>
  <li>
    I take responsibility for my actions whilst using ListList.com. I also take responsibility for any and all of my actions related to, or resulting from, my use of ListList.com. Further, I am solely responsible for any and all consequences of such my actions.
  </li>
  <li>
    I indemnify and hold harmless ListList and all of its owners, directors, officers, employees, and agents for any and all loss, harm, damage, costs, liability, and expense caused to them, whether intentionally or unintentionally, by my use of ListList.com, including but not limited to direct or indirect results of violations of any and all applicable laws.
  </li>
  <li>
    ListList may make changes to these terms at any time without notifying me. As a user, I am solely responsible for reading the most current version of the terms and conditions.
  </li>
  <li>
    By clicking "Agree to Terms," I electronically represent ("sign") that I agree to the above terms and further certify that I have read, and completely agree, to be legally bound by the ListList Terms of Use
  </li>
</ol>

templates/list_view.html
{% extends 'base.html' %}

{% block content %}
  <p class="lead">{{ queryset }}</p>
{% endblock content %}

templates/navbar.html
{% load staticfiles %}
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      {% url 'dashboard' as home_url %}
      <div class="navbar-brand">
        <embed src="{% static 'img/nav-logo.svg' %}" type="image/svg+xml" width="100" height="20" />
      </div>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li ><a href="{% url 'dashboard' %}">Home</a></li>
        <li><a href="{% url 'products:list' %}">Classifieds</a></li>
        <li><a href="{% url 'categories:category_home' %}">Categories</a></li>
      </ul>
      {% if not request.user.is_authenticated and not "/accounts/login" in request.get_full_path %}
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i> Login <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <form class="navbar-form" method="POST" action="{% url 'auth_login' %}">
                {% csrf_token %}
                <div class="form-group">
                  <input type="text" placeholder="Username" name="username" class="form-control">
                </div>
                <div class="form-group">
                  <input type="password" placeholder="Password" name="password" class="form-control">
                </div>
                <hr/>
                <button style="padding-left:6px; padding-right:6px;" type="submit" class="btn btn-primary btn-block">Login <i class="fa fa-sign-in"></i></button>
              </form>
              <p class="text-center btn btn-block"><a href="{% url 'auth_password_reset' %}">Forgot password?</a></p>
            </ul>
          </li>
          {% if not "/accounts/register/" in request.get_full_path %}
          <li><a href="{% url 'registration_register' %}"><i class="fa fa-user-plus"></i> Register</a></li>
          {% endif %}
        </ul>
      {% endif %}
      {% if request.user.is_authenticated %}
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'sellers:dashboard' %}">Post Ad <i class="fa fa-plus"></i></a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user|capfirst }} <span class="caret"></span></a>
            <ul class="dropdown-menu">
              {% if request.user.is_superuser or request.user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin <i class="fa fa-lock"></i></a></li>
              {% endif %}
              <li><a href="{% url 'sellers:dashboard' %}">Account <i class="fa fa-user"></i></a></li>
              <li><a href="{% url 'auth_logout' %}">Logout <i class="fa fa-sign-out"></i></a></li>
            </ul>
          </li>
        </ul>
      {% endif %}
    </div><!--/.navbar-collapse -->
  </div>
</nav>