listlist/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.gis import admin
from django.conf import settings

#import my app views
from products import urls as products_urls
from category import urls as urls_categories
# from tags import urls as tags_urls
from dashboard.views import DashboardView, LegalView
from sellers import urls as sellers_urls
from contact.views import ContactCreateView

from posts import urls as post_urls


urlpatterns = [
    #handle dashboard views
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    #handle django registration redux
    url(r'^accounts/', include('registration.backends.default.urls')),
    #handle admin sites
    url(r'^admin/', include(admin.site.urls)),
    #handle products app
    url(r'^classifieds/', include(products_urls, namespace='products')),
    #handle sellers app
    url(r'^seller/', include(sellers_urls, namespace='sellers')),
    #handle categories
    url(r'^categories/', include(urls_categories, namespace='categories')),
    #blog app
    url(r'^posts/', include(post_urls, namespace="posts")),
    #contact app
    url(r'^contact/$', ContactCreateView.as_view(), name="contact"),
    #dashboard legal view
    url(r'^legal/$', LegalView.as_view(), name='legal'),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sellers/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import (
        SellerDashboard,
        SellerProductDetailRedirectView,
        )

from products.views import (
    ProductCreateView,
    SellerProductListView,
    ProductUpdateView,
    ProductDeleteView,
)

urlpatterns = [
    url(r'^$', SellerDashboard.as_view(), name='dashboard'),
    url(r'^products/add/$', ProductCreateView.as_view(), name='product_create'),
    url(r'^products/$', SellerProductListView.as_view(), name='product_list'),
    url(r'^products/(?P<slug>[\w-]+)/edit/$', ProductUpdateView.as_view(), name='product_edit'),
    url(r'^products/(?P<slug>[-\w]+)/delete/$', ProductDeleteView.as_view(), name="product_delete"),
    url(r'^products/(?P<slug>[\w-]+)/$', SellerProductDetailRedirectView.as_view()),
]

tags/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import (
		TagDetailView,
		TagListView,
		)

urlpatterns = [
	url(r'^$', TagListView.as_view(), name='list'),
	url(r'^(?P<slug>[\w-]+)/$', TagDetailView.as_view(), name='detail'),
]

dashboard/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

sellers/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
# from django.contrib.auth.signals import user_logged_in

# import stripe
# from listlist.stripe_info import secret_key

# stripe.api_key = secret_key

# Create your models here.


class SellerAccount(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	managers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="manager_sellers", blank=True)
	active = models.BooleanField(default=True)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)


	def __unicode__(self):
		return str(self.user.username)

	def get_absolute_url(self):
		return reverse("products:vendor_detail", kwargs={"vendor_name": self.user.username})

# class SellerStripe(models.Model):
# 	user = models.OneToOneField(settings.AUTH_USER_MODEL)
# 	stripe_id = models.CharField(max_length=120, null=True, blank=True)
# 	phone_number = models.CharField(max_length=12, null=True, blank=True)
#
# 	def __unicode__(self):
# 		return str(self.user.username)
#
# def CreateStripeID(sender, user, request, **kwargs):
# 	new_id, created = SellerStripe.objects.get_or_create(user=user)
# 	if created:
# 		stripe_cust = stripe.Customer.create(email=user.email)
# 		new_id.stripe_id = stripe_cust.id
# 		new_id.save()
#
# user_logged_in.connect(CreateStripeID)

sellers/forms.py
from django import forms


class NewSellerForm(forms.Form):
	agree = forms.BooleanField(label='Agree to Terms', widget=forms.CheckboxInput)

dashboard/views.py
import random

from django.views.generic import View
from django.shortcuts import render

# Create your views here.

from products.models import CuratedProducts

class DashboardView(View):
	def get(self, request, *args, **kwargs):
		curated = CuratedProducts.objects.filter(active=True).order_by("?")

		context = {
			"curated": curated,
		}
		return render(request, "dashboard/view.html", context)

class LegalView(View):
	def get(self, request, *args, **kwargs):
		context = {
			"title": "Terms and Conditions",
		}
		return render(request, "dashboard/legal.html", context)

sellers/views.py
from django.shortcuts import render
from django.views.generic import View
from django.views.generic.base import RedirectView
from django.shortcuts import get_object_or_404
# Create your views here.

from django.views.generic.edit import FormMixin

from .forms import NewSellerForm
from .models import SellerAccount
from products.models import Product
from .mixins import SellerAccountMixin

class SellerProductDetailRedirectView(RedirectView):
	permanent = True
	def get_redirect_url(self, *args, **kwargs):
		obj = get_object_or_404(Product, slug=kwargs['slug'])
		return obj.get_absolute_url()

class SellerDashboard(SellerAccountMixin, FormMixin, View):
	form_class = NewSellerForm
	template_name = 'sellers/dashboard.html'
	success_url = "/seller/"

	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST)
		if form.is_valid():
			return self.form_valid(form)
		else:
			context = {
				'apply_form': form,
				'title': "Apply for Account",
			}
			return render(request, self.template_name, context)

	def get(self, request, *args, **kwargs):
		apply_form = self.get_form() #NewSellerForm()
		account = self.get_account()
		exists = account
		active = None

		context = {}

		if exists:
			active = account.active

		if not exists and not active:
			context["title"] = "Apply for Account"
			context["apply_form"] = apply_form
			context["active"] = active
		elif exists and not active:
			context["title"] = "Account Under Investigation"
			context["active"] = active
		elif exists and active:
			context["title"] = "Seller Dashboard"
			context["active"] = active
			#order by -timestamp and limit to top 4 on the seller dashboard
			context["products"] = self.get_products().order_by("-timestamp")[:4]
		else:
			pass

		return render(request, "sellers/dashboard.html", context)

	def form_valid(self, form):
		valid_data = super(SellerDashboard, self).form_valid(form)
		obj = SellerAccount.objects.create(user=self.request.user)
		return valid_data

templates/sellers/dashboard.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>{{ title }}</h1>
<hr>




{% if apply_form %}
<form method='POST' action=''> {% csrf_token %}
	<h3>Rules of the ListList Marketplace</h3>

	{% include 'legal.html' %}
	{{ apply_form|crispy }}
<br/>
<input class="btn btn-default" type='submit'/>
</form>
{% endif %}

{% if products %}
	<h3>My Most Recent Products</h3>
	{% include "products/product_list_snippet.html" with product_list=products %}
	<a class="btn btn-primary" href="{% url 'sellers:product_list' %}">View All <i class="fa fa-list"></i></a>
{% endif %}

{% if active != None and active != False %}
<a class="btn btn-success" href="{% url 'sellers:product_create' %}">Post Ad <i class="fa fa-plus-circle"></i></a>
{% endif %}



{% endblock %}

templates/sellers/product_list_view.html
{% extends "base.html" %}

{% block style %}

{% endblock style %}


{% block content %}
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>My Seller Products</h1>
    <hr>
  </div>
  <div class="col-sm-6 col-sm-offset-3">
    <div class="col-xs-9">
      <form method="GET" action="">
        <div class="input-group">
          <input type="text" value="{{ request.GET.q }}" name="q" class="form-control" placeholder="Search products..."/>
          <span class="input-group-btn">
            <input class="btn btn-primary" type="submit" value="Search"/>
          </span>
        </div>
      </form>
    </div>
    <div class="col-xs-3">
      <a class="btn btn-success" href="{% url 'sellers:product_create' %}">Post Ad <i class="fa fa-plus-circle"></i></a>
    </div>
    <br>
  </div>
  <div class="col-sm-8 col-sm-offset-2">
    <table class="table">
    	<thead class="thead-inverse">
    		<tr>
    			<th>
    				#
    			</th>
    			<th>
    				Image
    			</th>
    			<th>
    				Title
    			</th>
    			<th>
    				Price
    			</th>
    			<th>
    				Edit
    			</th>
    		</tr>
    	</thead>
    	{% for instance in product_list %}
    		<tbody>
    			<tr>
    	    	<th scope="row">
    	    		{{ instance.id }}
    	    	</th>
    	    	<td>
    		    	<a href='{{ instance.get_absolute_url }}'>
    		    		<img src='{{ instance.main_img.url }}' style='max-width:100px'/>
    					</a>
    	    	</td>
    				<td>
    	    		<a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a>
    	    	</td>
    	    	<td>
    					${{ instance.price }}
    	    	</td>
    	    	<td>
    					<a class="btn btn-info" href='{{ instance.get_edit_url }}'>Edit <i class="fa fa-pencil-square-o"></i></a> <a class="btn btn-warning" href="{{ instance.get_delete_url }}">Delete <i class="fa fa-trash"></i></a>
    	    	</td>
    			</tr>
    		</tbody>
    {% empty %}
    	<tbody>
    		<tr>
    			<td colspan="5">
    					No Products found.
    			</td>
    		</tr>
    	</tbody>
    {% endfor %}

    </table>

    {% if is_paginated %}
    <ul class="pagination nav navbar-nav">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><i class="fa fa-arrow-left"></i></a></li>
      {% endif %}
      {% if page_obj.paginator.num_pages > 1 %}
        {% for page in page_obj.paginator.page_range %}
          <li class="{% if page_obj.number == page  %}active{% endif %}"><a href="?page={{ page }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ page }}</a></li>
        {% endfor %}
      {% endif %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><i class="fa fa-arrow-right"></i></a></li>
      {% endif %}
    </ul>
    {% endif %}
  </div>
</div>




{% endblock %}